### ISSUE TITLE
cmake packaging

### ISSUE THREAD

**Issue by JohanMabille** [Nelson-numerical-software/nelson-minimalist-core#13]
I have started to look at the cmake packaging to make it easier for an external project to link with differnet parts of Nelson. I have some questions regarding which changes you would accept:

1] Install pattern

It is quite common on Linux and MacOS to install binaries directly under PREFIX/bin and PREFIX/lib, and to install public headers under PREFIX/include/PROJECT_NAME. The conda distribution provides a similar files tree on Windows, so that the install is quite similar on all the platforms. In the case of Nelson, adopting such a pattern means:
- the install directory becomes `${CMAKE_INSTALL_PREFIX}` instead of  `${CMAKE_INSTALL_PREFIX}Nelson-${Nelson_VERSION_MAJOR}.${Nelson_VERSION_MINOR}.${Nelson_VERSION_MAINTENANCE}`
- the platform subfolder under `bin` is removed.

Notice that these changes are independent.

2] CMake targets and exports

Exporting and installing the targets used to build the Nelson libraires would simplify a lot the link with them in downstream projects. One would simply write `find_package(Nelson)` followed by `target_link_libraries(myLib PRIVATE Nelson::interpreter)` for instance, and would get the include_directories and dependencies of `Nelson::interpreter` for free.

This requires two kinds of changes:
- The addition of a new `nelsonTargets.cmake` file, that would embed all the targets, as long as `NelsonConfig.cmake` and `NelsonVersionConfig.cmake`.
- rewriting the different `CMakeLists.txt` to use target properties instead of global properties

**Comment by Nelson-numerical-software** [comment]
Already reported by an fedora maintener, but it was not on the top of my todo list (snap and docker was enough until now for me)
Feel free to propose a PR :) or assign to me if you have not the time.
I will update the main repository to generalize this modification.
Thanks

**Comment by JohanMabille** [comment]
I'm happy to work on it ;)

**Comment by Nelson-numerical-software** [comment]
How to build and work locally ?
If I install nelson works but if I want to have local build. How to do ?
```bash
cmake .
make
```
What did I miss ?
