### ISSUE TITLE
[Help / Question] Use of `EvaluateCommand`

### ISSUE THREAD

**Issue by Hind-M** [Nelson-numerical-software/nelson-minimalist-core#14]
In the context of implementing a Jupyter kernel for Nelson (similar to this one for `cling` https://github.com/jupyter-xeus/xeus-cling), I figured using `EvaluateCommand` could be a good way to evaluate a given command. But then, I couldn't find the output of the evaluation. IIUC, an `AbstractSyntaxTree` is used for command storing but I was wondering how to get the output of the command after being executed? 
Thanks!

**Comment by Nelson-numerical-software** [comment]
`ArrayOfVector
EvaluateCommand(
    Evaluator* eval, int nLhs, const std::wstring& command, const std::wstring& catchCommand)
` 
available here:
https://github.com/Nelson-numerical-software/nelson-minimalist-core/blob/master/modules/core/src/cpp/EvaluateCommand.cpp#L90 and 
used by `eval` builtin in Nelson (not currently plugged in minimalist core, we can easily if you need)

https://nelson-numerical-software.github.io/nelson-website/help/en_US/eval.html

Try these examples in an standard nelson:
```matlab
theta = eval('cart2pol(3, 2, 1)')    % nLhs is 1
[theta, rho] = eval('cart2pol(3, 2, 1)') % nLhs is 2
[theta, rho, z] = eval('cart2pol(3, 2, 1)') % nLhs is 3
```

nLhs sets the numbers of variables to return. We know here nLhs because we have info by eval.
outputs are available in `ArrayOfVector`
`[theta, rho, z] = eval('cart2pol(3, 2, 1)')` 
--> theta is in ArrayOfVector[0]  
--> rho is in ArrayOfVector[1]  
--> z is in ArrayOfVector[2]  

to have content of rho in C++ (pseudo-code):
```C++
ArrayOfVector argsOut = EvaluateCommand(
    eval, 3, L"[theta, rho, z] = eval('cart2pol(3, 2, 1)')", L"");

ArrayOf RHO = argsOut[1];
NELSON_TYPE type = RHO.getDataClass() ;   // NLS_DOUBLE
Dimensions dims = RHO.getDimensions();   // dimension objects (1, 1) scalar
dims.getRows(); // 1
dims.getCols(); // 1
const double *ptrDouble = (const double *)RHO.getDataPointer();
ptrDouble[0]  // 3.6056
```


You can also interested by code used by `evalc` that allows to redirect output in io  EvaluateInterface
https://github.com/Nelson-numerical-software/nelson-minimalist-core/blob/master/modules/core/src/cpp/EvaluateCommand.cpp#L166
```matlab
TXT= evalc(' [theta, rho, z] = cart2pol(3, 2, 1)')
TXT = evalc('dir')
```

I hope this will help you, do not hesitate :)

**Comment by Hind-M** [comment]
Thanks :)
Ok, but then knowing `nLhs` is necessary, isn't it? If we want to evaluate a command in a generic way because we don't know the number of outputs generated for instance, could we think of computing nLhs in some way, just based on the command and its evaluation?
Also, what is the purpose of `catchCommand`? A sort of backup for the `command`?

**Comment by Nelson-numerical-software** [comment]
It seems that your needs is to get content of variables (?) 

Supposing that we try to have a C/C++ function "tunedEvaluateCommand" which returns value(s)
`ArrayOfVector evaluateCommand(commandLine)`

There is no way to know what the "user" will type on prompt.

example:
```matlab
a = cos(3); b = 4; d = 5 ; clear('a')
```

`ArrayOfVector returnedValues = evaluateCommand("a = cos(3); b = 4; d = 5 ; clear('a')")`

What do you expect as returned result in returnedValues by tunedEvaluateCommand ?
if 'b' and 'd' contents, there is no direct way to do this :/

Please also notice that one of the specificities of the language is that some functions can have different behavior with a different number of LHS
example with svd: 2 LHS vs 1 LHS result is not the same
```matlab
S = svd(A)
[U, S, V] = svd(A)
```

That we could do (pseudo code):

```C++
Context *context = eval->getContext();

stringVector variableNamesBeforeCurrentScope;
context->getCurrentScope()->getVariablesList(true, variablesCurrentScope);

try {
    eval->evaluateString("a = cos(3); b = 4; d = 5 ; clear('a')");
} catch {
    // ...
}

stringVector variableNamesAfterCurrentScope;
context->getCurrentScope()->getVariablesList(false, variableNamesAfterCurrentScope);

// find diff between variableNamesBefore and variableNamesAfter and  you can do:

ArrayOf valB = eval->getContext()->lookupVariable("b");
ArrayOf valD = eval->getContext()->lookupVariable("d");
```


About "Also, what is the purpose of catchCommand? A sort of backup for the command?"
It used for builtin language feature. It is a kind of try, catch (old language feature, for compatibility)
Try example of eval with Nelson ;)


sorry for delay ...

**Comment by Nelson-numerical-software** [comment]
I can try to prepare a more generic evolved function.
Reusable for some others projects

Because some case can be difficult to manage with previous proposition.
```
EvaluateCommand(eval, "a = 3;") // return 'a' value
EvaluateCommand(eval, "a = 4;") // 'a' value will be not see as created ('a' already existing before)

```
Do you need to have also output buffer and error buffer ?
```
EvaluateCommand(eval, "disp(3);") 
EvaluateCommand(eval, "k") // with k does not exist 
```

What do you do when the evaluation takes time ? 
```
EvaluateCommand(eval, "i=1;while(i < 100000, disp(i), i = i + 1, end") 
```

**Comment by Hind-M** [comment]
Oh getting the variables values from the context is an interesting feature!
After looking at the other kernels (xeus-cling, xeus-python etc), it seems that https://github.com/Nelson-numerical-software/nelson-minimalist-core/blob/master/modules/core/src/cpp/EvaluateCommand.cpp#L219 could be a good candidate for what we want - getting the result of the evaluation from the output buffer.
I couldn't test what we could do with nelson - in a kernel after integrating it as a package - (which is an ongoing work), but I've been mainly relying on the existing kernels code and on [documentation](https://xeus.readthedocs.io/en/latest/kernel_implementation.html#implementing-the-interpreter) so I could miss some things for now... 

> What do you do when the evaluation takes time ?

I guess we just wait :)

Otherwise, I realized that we may also need the `text_completion` module which is available in `nelson` but not in `nelson-minimalist-core`. It would be used to implement a feature where the given code is to be completed and the matches are returned.
For example:
https://github.com/jupyter-xeus/xeus-python/blob/main/src/xinterpreter.cpp#L167
and
https://github.com/jupyter-xeus/xeus-cling/blob/main/src/xinterpreter.cpp#L216
which is using
https://github.com/root-project/cling/blob/7aac81b4c017615d161f6e2b74d4997878a942b8/lib/Interpreter/Interpreter.cpp#L1007-L1059
Maybe use something with `CompleterHelper`?

**Comment by Hind-M** [comment]
Hi there,
I started testing nelson in my program :) and realized I can evaluate only simple commands, for example `a = 1` would work but then trying to use other specific functions doesn't.
For example `disp(a) `gives the following error:
```
Error: 
Undefined variable or function: disp
```
I tried using `import` but it seems that this isn't the keyword :) I couldn't find any mention of it in the documentation...
Thanks!

**Comment by Nelson-numerical-software** [comment]
`disp` is not plugged to minimalist core.
Currently, there is only `addpath`.

only operators, matrix manipulation are available.
Yes, It is minimalist

But it is maybe come the time to define what we need to add in this minimalist core  ;)

Currently: 
- you can load a function or a script with addpath see demo.zip in https://github.com/Nelson-numerical-software/nelson-minimalist-core/issues/11
- create a matrix, string, character vector, cell, struct
```matlab
A = {'N', 'el'; 's', 'on'}
B = ["Nelson", "this"; "is", "string matrix"]
C = 'a character vector'
D = 1:0.5:3
D * .5
[1:10] * [1:10]'
[1:10] .* [1:10]'
[1:10] / 3
[1:10] .^3
```

**Comment by Nelson-numerical-software** [comment]
all keywords are also available as part of language
https://github.com/Nelson-numerical-software/nelson-minimalist-core/blob/master/modules/interpreter/src/cpp/Keywords.cpp#L22

```matlab
for k = 1:2:10
k
end
```

**Comment by Nelson-numerical-software** [comment]
Did I answer to your question @Hind-M  ?

**Comment by Hind-M** [comment]
Yes, thank you! :)
