### ISSUE TITLE
Bug in `text_completion` ?

### ISSUE THREAD

**Issue by Hind-M** [Nelson-numerical-software/nelson-minimalist-core#23]
I realized when using `FileCompleter` and `VariableCompleter` available in the `text_completion` module that they are not considering if the retrieved files or variables start with the given `prefix` to complete. I just wanted to check if this wasn't done on purpose, and in that case, open a PR to fix it.
Note that `BuiltinCompleter` and `MacroCompleter` do consider that.

**Comment by Nelson-numerical-software** [comment]
Good point 
- for FileCompleter it does not seem to be a trouble
prefix is filtered in fact by  splitpath(prefix)
![image](https://user-images.githubusercontent.com/23081266/212728565-def3d447-eff8-4c0c-a409-fea6026ba1a1.png)
![image](https://user-images.githubusercontent.com/23081266/212728660-1217e871-7d8d-4e07-9693-11d12ae5f54c.png)
![image](https://user-images.githubusercontent.com/23081266/212740813-5f32a157-6a04-4927-a6a1-2d29df1f60ce.png)

Have you an example to show me that it is not enough (may, I miss something ?)

- for Variable it is a bug. (easy to fix=

Currently completion is used by text editor and not console (not finished feature for console) kernel will be the real test :)

**Comment by Hind-M** [comment]
Thanks! Yeah actually I just had a problem with `VariableCompleter` and then checked the others. I guessed, quite hastily, since `FileCompleter` didn't use `starts_with` that it didn't filter but it does!
