### ISSUE TITLE
Add a tag on `nelson-minimalist-core` to use for package availability on conda-forge

### ISSUE THREAD

**Issue by Hind-M** [Nelson-numerical-software/nelson-minimalist-core#31]
In order to integrate `nelson` in the `xeus-nelson` kernel and have a first version of it, we need to make `nelson` available as a package on conda-forge (https://github.com/conda-forge/staged-recipes/pull/21841).
This requires to build from a tarball, and therefore to have an existing tag on `nelson-minimalist-core`, could be `0.1.0`. Are you okay with that?
Regarding the [PR](https://github.com/conda-forge/staged-recipes/pull/21841) on conda-forge mentioned above, I was thinking of adding you as a maintainer of the recipe since you are the creator/owner of nelson, but no obligation of commitment of your own (more of a rights granting) :)
Can you confirm that this is alright?

**Comment by Nelson-numerical-software** [comment]
There are some modifications to do in:
https://github.com/Nelson-numerical-software/nelson-minimalist-core/blob/master/modules/commons/src/include/Nelson_VERSION.h.in
https://github.com/Nelson-numerical-software/nelson-minimalist-core/blob/master/modules/commons/src/include/Nelson_VERSION.h.vc

#define NELSON_PRODUCT_NAME "Nelson"  --> nelson-minimalist-core
and versions too

I will modifiy to 0.1.0
I will do tonight (if there is no time pressure)

It will be with pleasure to have the rights on the repo to maintain

(thanks)

**Comment by Nelson-numerical-software** [comment]
https://github.com/Nelson-numerical-software/nelson-minimalist-core/releases/tag/v0.1.0

**Comment by Hind-M** [comment]
Great, thanks!
