### ISSUE TITLE
[Question] io support in wasm 

### ISSUE THREAD

**Issue by Nelson-numerical-software** [Nelson-numerical-software/nelson-minimalist-core#49]
in environment wasm, does it interesting/possible to have features as: 
- `cd` ,  `pwd` , `mkdir` , `ls` (using c++ standard library)
playing with jupyter lite, it seems to be supported with python kernel ('/drive')
Does it require somethings special ?
- read/save files 
it is already possible to read .m , so i suppose that it is possible ?
any limitation ?

- is it possible to create tempory files in wasm too ?

(Thanks @JohanMabille)

**Comment by Nelson-numerical-software** [comment]
builtin using io:
  `pwd`, `dir`
  `cd`, `isdir`
  `isfolder`, `isfile`
  `fileparts`, `mkdir`
  `relativepath`, `rmdir`
  `copyfile`, `diff_file`
  `rmfile`, `pathsep`
  `filesep`, `fullpath`
  `tempdir`, `userdir`, `fullfile`

I hope that it will be compatible with wasm

**Comment by JohanMabille** [comment]
Sorry for the lae reply, I think you can emulate a filesystem, but it does not correspond to anything on your computer. I don't know the limitations as I have not worked on this, @martinRenou knows more than me.

**Comment by Nelson-numerical-software** [comment]
We had the answer with version 0.3 :) 
It works
