### ISSUE TITLE
Windows build with cmake

### ISSUE THREAD

**Issue by JohanMabille** [Nelson-numerical-software/nelson-minimalist-core#6]
Hi,

I can see in the [CmakeLists.txt](https://github.com/Nelson-numerical-software/nelson-minimalist-core/blob/e5dee694ab8ec5fa8842ebdef54970e88989ff7d/CMakeLists.txt#L10) that it is not possible to build nelson with cmake on Windows. Are you open to remove this constraint? If it was introduced because of a technical issue that you don't have the time to deal with, I'm happy to help to fix it.

**Comment by Nelson-numerical-software** [comment]
Hi,
Currently, It is not managed because it is easier for me to use Visual studio on Windows (native tools).
In this repo, no file require some specific optimization but in main repo. some files required some optimization only for windows.
Feel free to contribute.

**Comment by Nelson-numerical-software** [comment]
fixed with https://github.com/Nelson-numerical-software/nelson-minimalist-core/pull/43

**Comment by Nelson-numerical-software** [comment]
some warnings again to fix but it works
